numpy exercises

1. Import the numpy package under the name `np` 

In [12]:
import numpy as np

2. Create a null vector of size 10

In [49]:
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a null vector of size 10 but the fifth value which is 1

In [22]:
null_vector = np.zeros(10)

null_vector[4] = 1

print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


4. Create a vector with values ranging from 10 to 49 

In [25]:
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


5. Create a 3x3 matrix with values ranging from 0 to 8

In [32]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


6. Find indices of non-zero elements from [1,2,0,0,4,0]


In [36]:
arr = [1, 2, 0, 0, 4, 0]

non_zero_indices = np.nonzero(arr)[0]
print(non_zero_indices) 

[0 1 4]


7. Create a 3x3 identity matrix 

In [81]:
array_3D = np.identity(3)

print(array_3D) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


8. Create a 3x3x3 array with random values

In [45]:
x = np.random.random((3, 3, 3))

print(x) 

[[[0.19520917 0.52525158 0.44124188]
  [0.91145766 0.6415115  0.5980215 ]
  [0.41136849 0.35441075 0.14968843]]

 [[0.70260271 0.8919862  0.0519077 ]
  [0.97727694 0.67984508 0.26546481]
  [0.17751267 0.90192656 0.29435027]]

 [[0.0169255  0.36070871 0.02007103]
  [0.33356214 0.141253   0.35004624]
  [0.93568744 0.23938505 0.7520118 ]]]


9. Create a 10x10 array with random values and find the minimum and maximum values

In [110]:
x = np.random.random((10, 10))
print(x)
print(x.min())
print(x.max())

[[0.8332209  0.12549071 0.71593501 0.1698681  0.65915798 0.99637193
  0.68833474 0.59399858 0.74533849 0.13710767]
 [0.41724541 0.81897551 0.55674434 0.44805213 0.53830475 0.74288767
  0.28269272 0.77935725 0.25202718 0.74714628]
 [0.03682389 0.99281459 0.74700793 0.38439951 0.78914269 0.31485795
  0.03590979 0.85576885 0.9729716  0.16193393]
 [0.34391515 0.69523132 0.04566469 0.09352373 0.64849011 0.95131556
  0.64477581 0.10012374 0.29501163 0.42259333]
 [0.74515076 0.55847563 0.87821899 0.25875591 0.75676863 0.84763571
  0.9130693  0.45608906 0.04518376 0.92414441]
 [0.97926037 0.40414464 0.29341858 0.76012765 0.02339621 0.78866138
  0.96370694 0.72592898 0.56891506 0.21036022]
 [0.62175632 0.20612741 0.93166785 0.52789368 0.35128281 0.38181913
  0.30122887 0.56423503 0.66466169 0.05144574]
 [0.82582227 0.48388217 0.50789348 0.47064821 0.18921544 0.46127259
  0.07584725 0.71065901 0.59035485 0.19565487]
 [0.15370232 0.41906409 0.15017576 0.42539534 0.45823267 0.61058206
  0.45232443

10. Create a random vector of size 30 and find the mean value

In [120]:
x=np.random.random(30)
print(x.mean())

0.5433705144476172


11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [148]:
x = np.diag([1,2,3,4], k=-1)
print(x)

#1+np.arange(4)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


12. Normalize a 5x5 random matrix

In [83]:
x = np.random.random((5,5))
x = (x - np.mean (x)) / (np.std (x))
print(x)

[[-1.4752535  -1.22948271  1.55549729 -1.36993422  1.2154104 ]
 [ 0.50869645  1.49900056 -0.90782823  0.58696115  0.83944   ]
 [-1.1734663   0.50177306  0.3705921  -0.244027    0.4235318 ]
 [ 1.62332084  0.9170799  -1.08198709  0.22012364  1.03089081]
 [-0.46558913 -0.33838888 -0.81661125 -1.11191681 -1.07783288]]


13. How to find common values between two arrays?

In [92]:
X1 = np.random.randint(0,5,10)
X2 = np.random.randint(0,5,10)
print(np.intersect1d(X1,X2))

[1 2 3 4]


14. Create a random vector of size 10 and sort it

In [104]:
X=np.random.random(10)
X.sort()
print(X)

[0.1136641  0.16146315 0.3335479  0.34210378 0.34784726 0.70502664
 0.75453805 0.78181658 0.86144695 0.92341378]


15. Create random vector of size 10 and replace the maximum value by 0

In [107]:
X=np.random.random(10)
max_value=X.argmax(0)
print(max_value)

9


16. Subtract the mean of each row of a matrix

In [140]:
X = np.random.rand(7, 14)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[ 0.06433766,  0.04177669,  0.20099815, -0.1215192 , -0.36115762,
         0.02485466, -0.23175156, -0.07549413,  0.26624752, -0.32077969,
        -0.35637514,  0.45245293, -0.04119347,  0.45760318],
       [ 0.20094438,  0.01920276, -0.52927631,  0.29826348,  0.05093419,
         0.30866835, -0.44444133, -0.49088981,  0.25944689, -0.07518952,
        -0.31674164,  0.14030744,  0.4212561 ,  0.15751505],
       [ 0.23903337,  0.04944485,  0.35377397,  0.0455795 ,  0.00572213,
        -0.18094888,  0.05342931, -0.32722472,  0.15264099,  0.20093488,
         0.20136034, -0.469021  , -0.49953176,  0.17480702],
       [-0.35175613,  0.38861699, -0.04358659,  0.06268705, -0.21881295,
         0.18274954,  0.05183008,  0.28112888,  0.15612255, -0.12812956,
         0.09025601, -0.06251109, -0.38417892, -0.02441588],
       [ 0.38678946, -0.00516738, -0.19785129,  0.00547913,  0.07376418,
        -0.40611708, -0.35121954,  0.23849275, -0.04734122, -0.01534071,
        -0.0280093 ,  0.42

17. How to get the n largest values of an array

In [157]:
X = np.arange(10000)
np.random.shuffle(X)
n = 5
print (X[np.argsort(X)[-n:]])

[9995 9996 9997 9998 9999]


In [ ]:
18.Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 

In [187]:
x = np.arange(15).reshape(3,5)
np.where(x>4, x**2, x)

array([[  0,   1,   2,   3,   4],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

In [181]:
help(np.where)

Help on _ArrayFunctionDispatcher in module numpy:

where(...)
    where(condition, [x, y], /)

    Return elements chosen from `x` or `y` depending on `condition`.

    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.

    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.

    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.

    See Also
    --------
    choose
    nonzero : The function that is called when x and y are om